global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/recording-rules.yml
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: api-uptime
    metrics_path: /health/prometheus
    dns_sd_configs:
      - names:
          - api
        type: A
        port: 8080

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
